# Generated by Django 4.2.1 on 2023-10-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0003_group_person_membership_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
