# Generated by Django 4.2.1 on 2023-10-25 02:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0004_remove_group_members'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('phong', django.db.models.manager.Manager()),
            ],
        ),
    ]
